const GET_POKEMONS = "GET_POKEMONS";
const GET_TYPES = "GET_TYPES";
const GET_POKEMON_BY_ID = "GET_POKEMON_BY_ID";
const GET_POKEMON_BY_NAME = "GET_POKEMON_BY_NAME";
const PAGINATE = "PAGINATE";
const FILTER_BY_TYPES = "FILTER_BY_TYPES";
const ORDER_ALPHABETICALLY = "ORDER_ALPHABETICALLY";
const FILTER_BY_ORIGIN = "FILTER_BY_ORIGIN";
const FILTER_BY_ATTACK = "FILTER_BY_ATTACK";
const CREATE_POKEMON = "CREATE_POKEMON";
const CLEAR_PAGINATION = "CLEAR_PAGINATION";
const CLEAR_DETAIL = "CLEAR_DETAIL";

export {
  GET_POKEMONS,
  GET_TYPES,
  GET_POKEMON_BY_ID,
  GET_POKEMON_BY_NAME,
  PAGINATE,
  FILTER_BY_TYPES,
  ORDER_ALPHABETICALLY,
  FILTER_BY_ORIGIN,
  FILTER_BY_ATTACK,
  CREATE_POKEMON,
  CLEAR_PAGINATION,
  CLEAR_DETAIL
}