const GET_POKEMONS = "GET_POKEMONS";
const GET_TYPES = "GET_TYPES";
const GET_POKEMON_BY_ID = "GET_POKEMON_BY_ID";
const GET_POKEMON_BY_NAME = "GET_POKEMON_BY_NAME";
const PAGINATE = "PAGINATE";

export {
  GET_POKEMONS,
  GET_TYPES,
  GET_POKEMON_BY_ID,
  GET_POKEMON_BY_NAME,
  PAGINATE
}